# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
b1 = Book.create(title: "American Sniper", author: "Chris Kyle, Scott McEwen, Jim DeFelice", description: "A memoir about battlefield experiences in Iraq by the Navy SEALs sniper.", publisher: "Morrow/HarperCollins", language: "English", image:"/assets/AmericanSniper.jpg", totalBooks: 10, availableBooks: 10)
b2 = Book.create(title: "Unbroken", author: "Laura Hillenbrand", description: "An Olympic runnerâ€™s story of survival as a prisoner of the Japanese in World War II after his plane went down over the Pacific.", publisher: "Random House", language: "English", image:"/assets/UnBroken.jpg", totalBooks: 10, availableBooks: 10)
b3 = Book.create(title: "Wild", author: "Cheryl Strayed", description: "A womanâ€™s account of the life-changing 1,100-mile solo hike she took along the Pacific Crest Trail in 1995.", publisher: "Vintage", language: "English", image:"/assets/Wild.jpg", totalBooks: 10, availableBooks: 10)
b4 = Book.create(title: "The Boys in the Boat", author: "Daniel James", description: "A group of American rowers pursued gold at the 1936 Berlin Olympic Games.", publisher: "Penguin", language: "English", image:"/assets/TheBoysintheBoat.jpg", totalBooks: 10, availableBooks: 10)
b5 = Book.create(title: "Alan Turing: The Enigma", author: "Andrew Hodges", description: "The presiding mathetmatician and decoding force at Bletchley Park, the center that cracked the German Enigma code,", publisher: "Princeton University", language: "English", image:"/assets/AlanTuringTheEnigma.jpg", totalBooks: 10, availableBooks: 10)
b6 = Book.create(title: "Outliers", author: "Malcolm Gladwell", description: "Why some people succeed â€” it has to do with luck and opportunities as well as talent.", publisher: "Back Bay/Little, Brown", language: "English", image:"/assets/Outliers.jpg", totalBooks: 10, availableBooks: 10)
b7 = Book.create(title: "The Power of Habit", author: "Charles Duhigg", description: "An examinatino of the science behind habits, how we form them and break them.", publisher: "Random House", language: "English", image:"/assets/ThePowerofHabit.jpg", totalBooks: 10, availableBooks: 10)
b8 = Book.create(title: "A Brief History of Time", author: "Stephen W. Hawking", description: "The British cosmologist reviews efforts to create a unified theory of the universe.", publisher: "Bantam", language: "English", image:"/assets/ABriefHistoryofTime.jpg", totalBooks: 10, availableBooks: 10)
b9 = Book.create(title: "10% Happier", author: "Dan Harris", description: "A co-anchor of \"Nightline\" reports on the science and spiritual basis of meditation and how it has improved his life.", publisher: "Dey St.", language: "English", image:"/assets/10percentHappier.jpg", totalBooks: 10, availableBooks: 10)
b10 = Book.create(title: "The New Jim Crow", author: "Michelle Alexander", description: "A law professor takes aim at the â€œwar on drugsâ€ and its impact on black men.", publisher: "New Press", language: "English", image:"/assets/TheNewJimCrow.jpg", totalBooks: 10, availableBooks: 10)
b11 = Book.create(title: "Harry Potter and the Philosopher's Stone", author: "J.K.Rowling", publisher: "Bloomsbury Publishing", language: "English", description: "Harry Potter has never even heard of Hogwarts when the letters start dropping on the doormat at number four, Privet Drive. Addressed in green ink on yellowish parchment with a purple seal, they are swiftly confiscated by his grisly aunt and uncle. Then, on Harry’s eleventh birthday, a great beetle-eyed giant of a man called Rubeus Hagrid bursts in with some astonishing news: Harry Potter is a wizard, and he has a place at Hogwarts School of Witchcraft and Wizardry. An incredible adventure is about to begin! ", totalBooks: 20, availableBooks: 20, image:"/assets/Harry_potter_and_the_philosophers_book.jpg")
b12 = Book.create(title: "Harry Potter and the Chamber of Secrets", author: "J.K.Rowling", publisher: "Bloomsbury Publishing", language: "English", description: "Harry Potter’s summer has included the worst birthday ever, doomy warnings from a house-elf called Dobby, and rescue from the Dursleys by his friend Ron Weasley in a magical flying car! Back at Hogwarts School of Witchcraft And Wizardry for his second year, Harry hears strange whispers echo through empty corridors – and then the attacks start. Students are found as though turned to stone … Dobby’s sinister predictions seem to be coming true.", totalBooks: 20, availableBooks: 20, image:"/assets/Harry_potter_and_the_chamber_of_secrets_book_cover.jpg")
b13 = Book.create(title: "Harry Potter and the Prisoner of Azkaban", author: "J.K.Rowling", publisher: "Bloomsbury Publishing", language: "English", description: "When the Knight Bus crashes through the darkness and screeches to a halt in front of him, it’s the start of another far from ordinary year at Hogwarts for Harry Potter. Sirius Black, escaped mass-murderer and follower of Lord Voldemort, is on the run – and they say he is coming after Harry. In his first ever Divination class, Professor Trelawney sees an omen of death in Harry’s tea leaves … But perhaps most terrifying of all are the Dementors patrolling the school grounds, with their soul-sucking kiss …", totalBooks: 20, availableBooks: 20, image:"/assets/Harry_potter_and_the_prisoner_of_azkaban.jpg")
b14 = Book.create(title: "Harry Potter and the Goblet of Fire", author: "J.K.Rowling", publisher: "Bloomsbury Publishing", language: "English", description: "The Triwizard Tournament is to be held at Hogwarts. Only wizards who are over seventeen are allowed to enter – but that doesn’t stop Harry dreaming that he will win the competition. Then at Hallowe’en, when the Goblet of Fire makes its selection, Harry is amazed to find his name is one of those that the magical cup picks out. He will face death-defying tasks, dragons and Dark wizards, but with the help of his best friends, Ron and Hermione, he might just make it through – alive!", totalBooks: 20, availableBooks: 20, image:"/assets/Harry_potter_and_the_goblet_of_fire.jpg")
b15 = Book.create(title: "Harry Potter and the Order of the Phoenix", author: "J.K.Rowling", publisher: "Bloomsbury Publishing", language: "English", description: "Dark times have come to Hogwarts. After the Dementors’ attack on his cousin Dudley, Harry Potter knows that Voldemort will stop at nothing to find him. There are many who deny the Dark Lord’s return, but Harry is not alone: a secret Order gathers at Grimmauld Place to fight against the Dark forces. Harry must allow Professor Snape to teach him how to protect himself from Voldemort’s savage assaults on his mind. But they are growing stronger by the day and Harry is running out of time …", totalBooks: 20, availableBooks: 20, image:"/assets/Harry_potter_and_the_order_of_phoenix.jpg")
b16 = Book.create(title: "Harry Potter and the Half-Blood Prince", author: "J.K.Rowling", publisher: "Bloomsbury Publishing", language: "English", description: "When Dumbledore arrives at Privet Drive one summer night to collect Harry Potter, his wand hand is blackened and shrivelled, but he does not reveal why. Secrets and suspicion are spreading through the wizarding world, and Hogwarts itself is not safe. Harry is convinced that Malfoy bears the Dark Mark: there is a Death Eater amongst them. Harry will need powerful magic and true friends as he explores Voldemort’s darkest secrets, and Dumbledore prepares him to face his destiny ...", totalBooks: 20, availableBooks: 20, image:"/assets/Harry_potter_and_the_half_blood_prince.jpg")
b17 = Book.create(title: "Harry Potter and the Deathli Hallows", author: "J.K.Rowling", publisher: "Bloomsbury Publishing", language: "English", description: "As he climbs into the sidecar of Hagrid’s motorbike and takes to the skies, leaving Privet Drive for the last time, Harry Potter knows that Lord Voldemort and the Death Eaters are not far behind. The protective charm that has kept Harry safe until now is broken, but he cannot keep hiding. The Dark Lord is breathing fear into everything Harry loves, and to stop him Harry will have to find and destroy the remaining Horcruxes. The final battle must begin – Harry must stand and face his enemy ...", totalBooks: 20, availableBooks: 20, image:"/assets/Harry_potter_and_the_deadly_hallows.jpg")
